import { Penerimaan } from '@/types/penerimaan'

export const mockPenerimaan: Penerimaan[] = [
  {
    id: 1722,
    Rusunawa: "Cigugur",
    Gedung: "A",
    Lantai: "I",
    Nomor: "1",
    Bulan: "Juli",
    Tanggal_Tagihan: "2025-07-01",
    Nama: "Fety Sumarni",
    Sewa: 365000,
    Parkir: null,
    Denda: null,
    Total_Tagihan: 365000,
    Jumlah_Pembayaran: 365000,
    Status_Pembayaran: "Lunas",
    Tanggal_Bayar: "2025-07-10",
    StatusRekonsiliasi: "Sudah Rekonsiliasi"
  },
  {
    id: 1723,
    Rusunawa: "Cigugur",
    Gedung: "A",
    Lantai: "I",
    Nomor: "2",
    Bulan: "Juli",
    Tanggal_Tagihan: "2025-07-01",
    Nama: "Ar Farida",
    Sewa: 365000,
    Parkir: 22500,
    Denda: null,
    Total_Tagihan: 387500,
    Jumlah_Pembayaran: 387500,
    Status_Pembayaran: "Lunas",
    Tanggal_Bayar: "2025-07-09",
    StatusRekonsiliasi: "Sudah Rekonsiliasi"
  },
  {
    id: 1724,
    Rusunawa: "Cigugur",
    Gedung: "A",
    Lantai: "I",
    Nomor: "3",
    Bulan: "Juli",
    Tanggal_Tagihan: "2025-07-01",
    Nama: "Siti Nurjanah",
    Sewa: 365000,
    Parkir: 22500,
    Denda: 50000,
    Total_Tagihan: 437500,
    Jumlah_Pembayaran: 437500,
    Status_Pembayaran: "Lunas",
    Tanggal_Bayar: "2025-07-15",
    StatusRekonsiliasi: "Sudah Rekonsiliasi"
  },
  {
    id: 1725,
    Rusunawa: "Cigugur",
    Gedung: "B",
    Lantai: "II",
    Nomor: "5",
    Bulan: "Juli",
    Tanggal_Tagihan: "2025-07-01",
    Nama: "Ahmad Ridwan",
    Sewa: 365000,
    Parkir: 22500,
    Denda: null,
    Total_Tagihan: 387500,
    Jumlah_Pembayaran: 0,
    Status_Pembayaran: "Belum Lunas",
    Tanggal_Bayar: null,
    StatusRekonsiliasi: "Belum Rekonsiliasi"
  },
  {
    id: 1726,
    Rusunawa: "Karawang",
    Gedung: "A",
    Lantai: "III",
    Nomor: "12",
    Bulan: "Juni",
    Tanggal_Tagihan: "2025-06-01",
    Nama: "Dewi Lestari",
    Sewa: 365000,
    Parkir: null,
    Denda: null,
    Total_Tagihan: 365000,
    Jumlah_Pembayaran: 365000,
    Status_Pembayaran: "Lunas",
    Tanggal_Bayar: "2025-06-08",
    StatusRekonsiliasi: "Sudah Rekonsiliasi"
  },
  {
    id: 1727,
    Rusunawa: "Karawang",
    Gedung: "B",
    Lantai: "I",
    Nomor: "3",
    Bulan: "Juni",
    Tanggal_Tagihan: "2025-06-01",
    Nama: "Budi Santoso",
    Sewa: 365000,
    Parkir: 22500,
    Denda: null,
    Total_Tagihan: 387500,
    Jumlah_Pembayaran: 387500,
    Status_Pembayaran: "Lunas",
    Tanggal_Bayar: "2025-06-12",
    StatusRekonsiliasi: "Sudah Rekonsiliasi"
  },
  {
    id: 1728,
    Rusunawa: "Karawang",
    Gedung: "A",
    Lantai: "II",
    Nomor: "8",
    Bulan: "Agustus",
    Tanggal_Tagihan: "2025-08-01",
    Nama: "Rina Marlina",
    Sewa: 365000,
    Parkir: 22500,
    Denda: null,
    Total_Tagihan: 387500,
    Jumlah_Pembayaran: 200000,
    Status_Pembayaran: "Sebagian",
    Tanggal_Bayar: "2025-08-05",
    StatusRekonsiliasi: "Belum Rekonsiliasi"
  },
  {
    id: 1729,
    Rusunawa: "Cibitung",
    Gedung: "A",
    Lantai: "I",
    Nomor: "1",
    Bulan: "Agustus",
    Tanggal_Tagihan: "2025-08-01",
    Nama: "Joko Widodo",
    Sewa: 365000,
    Parkir: null,
    Denda: null,
    Total_Tagihan: 365000,
    Jumlah_Pembayaran: 365000,
    Status_Pembayaran: "Lunas",
    Tanggal_Bayar: "2025-08-03",
    StatusRekonsiliasi: "Sudah Rekonsiliasi"
  },
  {
    id: 1730,
    Rusunawa: "Cibitung",
    Gedung: "B",
    Lantai: "II",
    Nomor: "7",
    Bulan: "Agustus",
    Tanggal_Tagihan: "2025-08-01",
    Nama: "Sri Mulyani",
    Sewa: 365000,
    Parkir: 22500,
    Denda: null,
    Total_Tagihan: 387500,
    Jumlah_Pembayaran: 0,
    Status_Pembayaran: "Belum Lunas",
    Tanggal_Bayar: null,
    StatusRekonsiliasi: "Belum Rekonsiliasi"
  },
  {
    id: 1731,
    Rusunawa: "Cibitung",
    Gedung: "A",
    Lantai: "III",
    Nomor: "15",
    Bulan: "September",
    Tanggal_Tagihan: "2025-09-01",
    Nama: "Hendra Gunawan",
    Sewa: 365000,
    Parkir: 22500,
    Denda: 75000,
    Total_Tagihan: 462500,
    Jumlah_Pembayaran: 462500,
    Status_Pembayaran: "Lunas",
    Tanggal_Bayar: "2025-09-20",
    StatusRekonsiliasi: "Sudah Rekonsiliasi"
  }
]
